// TRABALHO_NIVEL_5/Clientes/ANGULAR/livro-dados/livro-dados.component.ts
import { Component,OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent {
  router: Router;
  public editora: Editora[]=[]
  private servEditora=ControleEditoraService
  private servLivro=ControleLivrosService
  public titulo!:string; resumo!:string; editoraCod!:string
  public autores!: string[]
  constructor(rout:Router){this.router=rout}
  ngOnInit(){
    this.editora=new this.servEditora().getEditoras()
  }
  IncluirDados(form:any):void {
    form=form.value
    new this.servLivro().incluir(new Livro(
      "",
      Number(form.editoraForm),
      form.titulo,
      form.resumo,
      new this.servEditora().getNomeEditora(form.editoraForm),
      form.autores.split("\n")
    ))
    this.router.navigateByUrl('/livro-lista')
  }
}
<style>@import url("https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css");</style>
<h3>FORMULARIO</h3>
<form id="Form1" (ngSubmit)="IncluirDados(f)" #f="ngForm">
    <div class="form-group">
        <label required for="FormTitulo">Titulo</label>
        <input required type="text" name="titulo" id="InpTitulo" ngModel
        class="form-control"/>
    </div>
    <div class="form-group">
        <label for="FormResumo">Resumo</label>
        <textarea required id="InpResumo" name="resumo" ngModel
        class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="FormTitulo">Editora</label>
        <select id="InpEditora" required  name="editoraForm" ngModel
        class="form-control">
            <option *ngFor="let Edt of editora" class="form-control" value="{{Edt.codEditora}}">
                {{Edt.nome}}
            </option>
        </select>
    </div>
    <div class="form-group">
        <label for="FormTitulo">Autores(1) por linha</label>
        <textarea  id="InpAutores" name="autores" required ngModel
        class="form-control"></textarea>
    </div>
    <button type="submit" value="Submit" class="btn btn-primary">Salvar dados</button>
</form>

// TRABALHO_NIVEL_5/Clientes/REACT/LivroDados.js
import ControleEditora from "./controle/ControleEditora"
import ControleLivro from "./controle/ControleLivros"
import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import Livro from "./modelo/Livro"

var Editoras = new ControleEditora().getEditoras()
var Opcoes

function LinhaLivro() {
    const [Titulo, SetTitulo] = useState("")
    const [Resumo, SetResumo] = useState("")
    const [Autores, SetAutores] = useState("")
    const [CodEdit, SetCodEdit] = useState(0)
    Opcoes = (
        <select
        id="InpEditora"
        required
        className="form-control"
        onChange={(e) => {SetCodEdit(e.target.value)}}>
        <option key={-1} value={0}>--SELECIONE--</option>

        {Editoras.map((op) => {
            return (
            <option key={op.codEditora} value={op.codEditora}>
                {op.nome}
            </option>
            )
        })}
    </select>
    )

    const TratarCombo = (e) => {
        e.preventDefault()
        if (CodEdit !== 0) {
        new ControleLivro()
            .incluir(
                new Livro("", 
                Number(CodEdit), 
                Titulo, Resumo, 
                new ControleEditora().getNomeEditora(CodEdit), 
                Autores.split("\n")
            ))
            .then(() => {
            document.getElementById("InpTitulo").value = ""
            document.getElementById("InpResumo").value = ""
            document.getElementById("InpEditora").value = 0
            document.getElementById("InpAutores").value = ""
            })
        }
    }
    return (
        <div>
        <nav className="navbar bg-dark nav-start">
            <Link className="text-white NoTxtDec" to="/">
                CATALOGO
            </Link>
            <Link className="text-white NoTxtDec" to="/Adicionar">
                ADICIONAR
            </Link>
        </nav>
        <form id="Form1" onSubmit={(e) => TratarCombo(e)}>
            <div className="form-group">
                <label required htmlFor="FormTitulo">
                    Titulo
                </label>
                <input
                    required
                    type="text"
                    id="InpTitulo"
                    onChange={(e) => {
                    SetTitulo(e.target.value)
                    }}
                    className="form-control"></input>
            </div>
            <div className="form-group">
                <label htmlFor="FormResumo">Resumo</label>
                <textarea
                    required
                    id="InpResumo"
                    onChange={(e) => {
                    SetResumo(e.target.value)
                    }}
                    className="form-control"></textarea>
            </div>
            <div className="form-group">
                <label htmlFor="FormTitulo">Editora</label>
                {Opcoes}
            </div>
            <div className="form-group">
                <label htmlFor="FormTitulo">Autores(1) por linha</label>
                <textarea
                id="InpAutores"
                required
                onChange={(e) => {
                SetAutores(e.target.value)
                }}
                className="form-control"></textarea>
            </div>
            <button type="submit" value="Submit" className="btn btn-primary">
                Salvar dados
            </button>
        </form>
        </div>
    )
}
export default LinhaLivro
